service: alexaops

provider:
  name: aws
  region: eu-west-1
  runtime: python3.6
  memorySize: 128

# package:
#   exclude:
#     - test.py

functions:
  alexaInstanceControl:
    handler: lambda_function.lambda_handler
    events:
      - alexaSkill

plugins:
  - serverless-python-requirements
