service: alexaops

provider:
  name: aws
  region: eu-west-1
  runtime: python3.6
  memorySize: 128

# package:
#   exclude:
#     - test.py

plugins:
  - serverless-python-requirements

functions:
  alexaInstanceControl:
    handler: lambda_function.handler
    events:
      - alexaSkill

Outputs:
    FunctionArn:
      Description: The ARN for the Lambda function
      Value:
        "Fn::GetAtt": [ alexaInstanceControl, Arn ]
      Export:
        Name: ${self:service}:${opt:stage}:FunctionArn